### ISSUE TITLE
Intergration with Discord

### ISSUE THREAD

**Issue by chriscn** [chriscn/StaffChat#1]
The end goal for this project is to intergrate with Discord with the seperate channels so you can have two way communicaton. 
```yaml
discord:
  all: <id>
  staff: <id>
  admin: <id>
```
Where each of these ids are the id of the channels. You would require people to setup their own bot but that isn't that difficult.
