### ISSUE TITLE
Custom Channels

### ISSUE THREAD

**Issue by chriscn** [chriscn/StaffChat#3]
It would be nice to allow users to define as many custom or `VirtualChannel` as they'd like. I was thinking about acomplishing this through a list in the config. However that is proving more difficult. 
```yaml
channel:
  admin:
   - name: admin
   - permission_write: staffchat.admin.write
   - permisson_read: staffchat.admin.read
   - message_format: "&c[ADMIN]"
  staff:
   - permission_write: staffchat.staff.write
   - permisson_read: staffchat.staff.read
   - message_format: "&a[STAFF]"
  developer:
   - permission_write: staffchat.developer.write
   - permisson_read: staffchat.developer.read
   - message_format: "&e[DEVELOPER]"
```
However that is proving to be very difficult in Java with YAML. Maybe I should use JSON?
